In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [62]:
class SLRbyMe:
    def __init__(self):
        self.m=0
        self.b=0
    
    def fit(self, X_train, y_train):
        num=0
        den=0
        for i in range(X_train.shape[0]):
            num=num+((X_train[i]-X_train.mean()))*(y_train[i]-y_train.mean())
            den=den+((X_train[i]-X_train.mean())**2)
        self.m=num/den
        self.b=y_train.mean()-(self.m*X_train.mean())

    def predict(self, X_test):
        y_pred=self.m*X_test+self.b
        return y_pred

In [63]:
data=pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Salary%20Data.csv')
data.head()

Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [64]:
X= data.iloc[:,0].values
y= data.iloc[:,-1].values

In [65]:
X

array([ 1.1,  1.2,  1.3,  1.5,  2. ,  2.2,  2.5,  2.9,  3. ,  3.2,  3.2,
        3.5,  3.7,  3.8,  3.9,  4. ,  4. ,  4.1,  4.3,  4.5,  4.7,  4.9,
        5.1,  5.3,  5.5,  5.9,  6. ,  6.2,  6.5,  6.8,  7.1,  7.9,  8.2,
        8.5,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [66]:
y

array([ 39343,  42774,  46205,  37731,  43525,  39891,  48266,  56642,
        60150,  54445,  64445,  60000,  57189,  60200,  63218,  55794,
        56957,  57081,  59095,  61111,  64500,  67938,  66029,  83088,
        82200,  81363,  93940,  91000,  90000,  91738,  98273, 101302,
       113812, 111620, 109431, 105582, 116969, 112635, 122391, 121872],
      dtype=int64)

In [67]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [68]:
lr=SLRbyMe()

In [69]:
lr.fit(X_train,y_train)

In [70]:
lr.predict(X_test)

array([ 84174.40735952,  55284.72051045,  62025.6474419 ,  35061.9397161 ,
        36987.91883938,  92841.31341423,  61062.65788026, 115953.06289349])